### ISSUE TITLE
FormSerializationWriter does not actually write content to the request

### ISSUE THREAD

**Issue by AaronAtDuo** [microsoft/kiota-serialization-form-python#14]
**Environment**

- Python Version
3.11.2
- kiota-serialization-form version:
0.1.0
- OS:
Debian 12.5 (via docker)

**Stack trace (if available)**
N/A

**Describe the bug**
(I'm not sure if this is a bug, or just "we haven't gotten to this yet")
When using the FormSerializationWriter, it does not actually write any content to the RequestInformation.

**To Reproduce**
Generate a python client with the provided yaml and run the provided script.  It will demonstrate that the body is not written to the request.
[bug-openapi.txt](https://github.com/microsoft/kiota-serialization-form-python/files/14589473/bug-openapi.txt)
[fsw-bug.txt](https://github.com/microsoft/kiota-serialization-form-python/files/14589474/fsw-bug.txt)

**Expected behavior**
The body object should be in the content

**Screenshots**

**Additional context**
I believe the problem is because at
https://github.com/microsoft/kiota-abstractions-python/blob/main/kiota_abstractions/request_information.py#L179
the 'write_object_value' method is called with a None key and the body object, but in the FormSerializationWriter
https://github.com/microsoft/kiota-serialization-form-python/blob/main/kiota_serialization_form/form_serialization_writer.py#L189
a None key means that nothing at all happens.  The documentation indicates the key is supposed to be optional.

**Comment by baywet** [comment]
Hi @AaronAtDuo 
Thanks for the very detailed information here and for using kiota.
Assuming you're using the latest version of kiota (1.12) and of all kiota python dependencies, this sounds like a bug.
Would you be willing to submit a PR to address it?

**Comment by shemogumbe** [comment]
Hello, I have been able to reproduce this, the body is indeed empty.

Looking into serialization to find out why

**Comment by baywet** [comment]
@shemogumbe if you compare [the dotnet implementation](https://github.com/microsoft/kiota-dotnet/blob/c198508ec738bc780e5816c33847880ddd5981ff/src/serialization/form/FormSerializationWriter.cs#L190) with the [python one](https://github.com/microsoft/kiota-serialization-form-python/blob/e345d77e0d207bcbec83f58ea14ad370fbbdf949/kiota_serialization_form/form_serialization_writer.py#L189) you'll spot that the dotnet one DOES NOT check for the key being null, it simply writes the object if we're at the "first level of depth".
I think we should align the implementation in python here.
Can you take this on please?

**Comment by shemogumbe** [comment]
This is slightly similar to  what I worked on for falsy vs null checks, testing then doing it for all the writers if it's the case

**Comment by shemogumbe** [comment]
Initial investigation
```
key: None, value: FooPostRequestBody(additional_data={}, bar='baz'), additional_values_to_merge: ()
```

checking why key is None, which leads to an empty string upon serialization

**Comment by AaronAtDuo** [comment]
@shemogumbe I believe it is explicitly sent as None at https://github.com/microsoft/kiota-abstractions-python/blob/main/kiota_abstractions/request_information.py#L179

**Comment by shemogumbe** [comment]
Making changes in both the form_serialization_writer and the request_information abstract class to fix
